version: "3.5"

services:
  auth-service:
    container_name: auth-service
    build: 
      context: .
      dockerfile: AuthenticationServer/Dockerfile
    ports:
      - 7137:7137
  auction-service:
    container_name: auction-service
    build:
      context: .
      dockerfile: AuctionService/Dockerfile
    ports:
      - 7061:7061
  auction-live-service:
    container_name: auction-live-service
    build:
      context: .
      dockerfile: AuctionLiveService/Dockerfile
    ports:
      - 7019:7019
  postgresql-auction-service:
    image: postgres:14.4
    container_name: postgresql-auction-service
    environment:
      - POSTGRES_USER=auction_service
      - POSTGRES_PASSWORD=auctionpsqlpass218
      - POSTGRES_DB=auction
    ports:
      - 5432:5432
  postgresql-auth-service:
    image: postgres:14.4
    container_name: postgresql-auth-service
    environment:
      - POSTGRES_USER=auth_service
      - POSTGRES_PASSWORD=authpsqlpass218
      - POSTGRES_DB=auth
      - PGPORT=5431
    ports:
      - 5431:5431