version: "3.5"

services:
  auth-service:
    container_name: auth-service
    build: 
      context: .
      dockerfile: AuthenticationServer/Dockerfile
    ports:
      - 7137:7137
  auction-service:
    container_name: auction-service
    build:
      context: .
      dockerfile: AuctionService/Dockerfile
    ports:
      - 7061:7061
  auction-live-service:
    container_name: auction-live-service
    build:
      context: .
      dockerfile: AuctionLiveService/Dockerfile
    ports:
      - 7019:7019
  postgresql-auctions-service:
    image: postgres:14.4
    container_name: postgresql-auctions-service
    environment:
      - POSTGRES_USER=glebevlakhov
      - POSTGRES_PASSWORD=psqlpass218
      - POSTGRES_DB=auctions
    ports:
      - 5431:5432
  postgresql-users-service:
    image: postgres:14.4
    container_name: postgresql-users-service
    environment:
      - POSTGRES_USER=glebevlakhov
      - POSTGRES_PASSWORD=psqlpass218
      - POSTGRES_DB=users
    ports:
      - 5432:5432